name: brainbox
dependencies:
  - python=3.8
  - nb_conda_kernels=2.3.1
  - numpy
  - seaborn
  - pandas
  - scipy
  - scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit=11.1
  - pip:
    - kornia
    - h5py<3.0.0