name: brainbox
dependencies:
  - python=3.7
  - nb_conda_kernels=2.3.0
  - numpy=1.16.2
  - seaborn=0.11.0
  - pandas=1.0.1
  - scipy=1.2.1
  - scikit-learn=0.23.2
  - pytables=3.6.1
  - pytorch::pytorch=1.7.0
  - pytorch::torchvision=0.8.0
  - pip:
    - kornia
    - shelves
    - h5py<3.0.0