name: brainbox
dependencies:
  - python=3.8
  - black
  - pytest
  - numpy
  - pandas
  - pytorch::pytorch
  - pytorch::torchvision
  - h5py
  - nb_conda_kernels=2.3.1
  - pip:
    - kornia
    - --editable .